# vim:fileencoding=utf-8:foldmethod=marker

# 字体
font_family CaskaydiaCoveNerdFont

# 禁用响铃
enable_audio_bell no

# 模糊
background_opacity 0.9
background_blur 7


# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
